name = "Adrenaline"
author = "UltraStorm"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0ea8fee47be26b5596d4bca26633f83d64b408fc526513adc686e717e19370d"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
