name = "Adrenaline"
author = "UltraStorm"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a44c37cb801ff77b8ab319fdf43af6c5aeb85ab2fe32cfb5fbf55dd14ffa426a"

[versions]
fabric = "0.14.8"
minecraft = "1.19.1"
