name = "Noradrenaline"
author = "exincore"
version = "2.0.0+1.14.7-mc1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28ba3d2d3b099f25ed56b8fdfc44ffeb3984a19aa6d860b2f7e49e0cf3144f87"

[versions]
minecraft = "1.19.4"
quilt = "0.19.2"
