name = "Noradrenaline"
author = "exincore"
version = "2.0.0+1.14.7-mc1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0a63de6d0ec647fade86903b2573f18a59e7444488138bf7cc67bc613cdf804"

[versions]
minecraft = "1.19.4"
quilt = "0.19.2"
