name = "Noradrenaline"
author = "exincore"
version = "2.0.0+1.14.7-mc1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23bcd4d3fc57ad26d25cae746762893c78c36b420fce48d3c16f8f4e1ff0f7b7"

[versions]
minecraft = "1.19.4"
quilt = "0.19.2"
