name = "Noradrenaline"
author = "exincore"
version = "2.0.0+1.14.7-mc1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74ff6c6e6283a6f8a6dae85c306095c753cf3bf0b5332516567ceb622da93b01"

[versions]
minecraft = "1.19.4"
quilt = "0.19.2"
