name = "Noradrenaline"
author = "exincore"
version = "2.0.0+1.14.7-mc1.18.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cae4ae5a5f3b93722cb264f28976b9b1c4a9722fd1f810b3909609197adecbb"

[versions]
minecraft = "1.18.2"
quilt = "0.19.2"
