name = "Noradrenaline"
author = "exincore"
version = "2.0.0+1.14.7-mc1.18.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b81b2446f1d0a3e2e3e2c6fef63e66ac89ed651400cdfdd3d7f52d8b458f8683"

[versions]
minecraft = "1.18.2"
quilt = "0.19.2"
