name = "Noradrenaline"
author = "exincore"
version = "2.0.0+1.14.7-mc1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55a5efee1b014c94a4e18d32a5ea266317b66640cfd0c48f0eeacb271aa3f95e"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
