name = "Noradrenaline"
author = "exincore"
version = "2.0.0+1.14.7-mc1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "773be175de84f52651fa665af0b50d61c8f9c1f84ec43b0eab57cc33d149036a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"
