name = "Adrenaline"
author = "UltraStorm"
version = "1.14.7+1.18.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc96db03e77968fb785344e7f5072acd2cc6dc48faa461b39c353bcf4585ee68"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
