name = "Noradrenaline"
author = "exincore"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91f2035c8d9f647b657dabd545760f35733baca66d5190d17116bce30b14705a"

[versions]
minecraft = "1.19.1"
quilt = "0.17.1"
