name = "Noradrenaline"
author = "exincore"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d4969b75b6fb6b86bccd771d0d6b04be3ce4b973def291fa433c941d0cdbeb5"

[versions]
minecraft = "1.19"
quilt = "0.17.1"
