name = "Noradrenaline"
author = "exincore"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9aff360845750be10b0b382b81a39a7da1064efab9b208ee87b27beef9abb068"

[versions]
minecraft = "1.19"
quilt = "0.17.1"
