name = "Noradrenaline"
author = "exincore"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce0b7af80117f41f350e3e459ca11ae5fbac4f0960d434667fab20ce141ea9f0"

[versions]
minecraft = "1.19"
quilt = "0.17.1"
