name = "Noradrenaline"
author = "exincore"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63b1744919d27d608d196962adfa3e04da00733e5b4a4934995fa6162a3ca655"

[versions]
minecraft = "1.19"
quilt = "0.17.1"
